### ISSUE TITLE
insecure platform when trying to start

### ISSUE THREAD

**Issue by nmann20** [dz0ny/leapcast#133]
I believe that I followed all the step to set this up correctly, but I am finding problems starting to run leap cast. It says that there is an insecure platform. 

I get this 
```
INFO:root:Starting SSDP server
INFO:root:Starting LEAP server
INFO:root:Loading Config-JSON from Google-Server
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): clients3.google.com
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "C:\Python27\Scripts\leapcast-script.py", line 9, in <module>
    load_entry_point('Leapcast', 'console_scripts', 'leapcast')()
  File "c:\leapcast-master\leapcast\__main__.py", line 38, in main
    leap_server.start()
  File "c:\leapcast-master\leapcast\services\leap.py", line 35, in start
    resp = requests.get(url=app_dict_url)
  File "C:\Python27\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

```

**Comment by FastDr1v3r** [comment]
I got the same problem... :( I can't run Leapcast.

**Comment by x8BitRain** [comment]
I uninstalled python 2.7.5 and installed 2.7.11 and it started working, note that you have to start the service with the path like this  "C:/Users/DieBagger/AppData/Local/Google/Chrome/Application/chrome.exe" rather than with backslashes ( \ ), it's working great.

**Comment by dobrakmato** [comment]
I added these two lines to leapcast's __main__.py file:

```
import requests
requests.packages.urllib3.disable_warnings()
```
That disabled urllib3 warnings about SNI. Then I also added `verify=False` to services/leap.py:35 to make the library not raise error. 

```
# load json-file
resp = requests.get(url=app_dict_url, verify=False)
```
